// gravitee-am-ui-next/src/lib/session/environment.tsx
/*
 * Copyright (C) 2015 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { createContext, use } from 'react';
import { Navigate, Outlet, useParams } from 'react-router-dom';
import type { Environment } from '../api/management-api';
import { useSession } from './session';

const EnvironmentContext = createContext<Environment | null>(null);

export function useCurrentEnvironment(): Environment {
    const environment = use(EnvironmentContext);
    if (!environment) {
        throw new Error('useCurrentEnvironment() called outside <EnvironmentScope>');
    }
    return environment;
}

/** Resolves `:envHrid` against the user's environments. `/auth/cockpit` lands on `/environments/<hrid>`. */
export function EnvironmentScope() {
    const { envHrid } = useParams();
    const { environments } = useSession();
    const environment = environments.find(env => envHrid !== undefined && env.hrids.includes(envHrid));

    if (!environment) {
        return <Navigate to="/" replace />;
    }
    return (
        <EnvironmentContext value={environment}>
            <Outlet />
        </EnvironmentContext>
    );
}

export function RootRedirect() {
    const { environments } = useSession();
    const first = environments[0];

    if (!first) {
        return <p className="p-6 text-sm text-muted-foreground">No environment is available to your account.</p>;
    }
    return <Navigate to={`/environments/${first.hrids[0]}`} replace />;
}

// gravitee-am-ui/src/app/environment/environment.component.ts
/*
 * Copyright (C) 2015 The Gravitee team (http://gravitee.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Subscription } from 'rxjs';

import { DomainService } from '../services/domain.service';
import { AuthService } from '../services/auth.service';
import { NavbarService } from '../components/navbar/navbar.service';
import { EnvironmentService } from '../services/environment.service';

@Component({
  selector: 'app-home',
  templateUrl: './environment.component.html',
  styleUrls: ['./environment.component.scss'],
})
export class EnvironmentComponent implements OnInit {
  readonly = true;
  envHrid: string;
  isLoading = true;
  subscription: Subscription;

  constructor(
    private router: Router,
    private domainService: DomainService,
    private authService: AuthService,
    private navbarService: NavbarService,
    private environmentService: EnvironmentService,
  ) {}

  ngOnInit() {
    this.subscription = this.environmentService.currentEnvironmentObs$.subscribe((environment) => {
      this.envHrid = environment.hrids.length > 0 ? environment.hrids[0] : environment.id;
      this.initDomains();
    });
  }
  initDomains() {
    // redirect user to the first domain, if any.
    this.domainService.list().subscribe((response) => {
      if (response.data?.length > 0) {
        this.router.navigate(['/environments', this.envHrid, 'domains', response.data[0].hrid]);
      } else {
        this.isLoading = false;
        this.readonly = !this.authService.hasPermissions(['domain_create']);
        this.navbarService.notifyDomain({});
      }
    });
  }
}

<!--

    Copyright (C) 2015 The Gravitee team (http://gravitee.io)

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

            http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<div *ngIf="!isLoading" class="environment-container">
  <div class="environment-content">
    <div class="environment-content-header">
      Integrate authentication and authorization to secure access for your applications and APIs.
    </div>
    <div class="environment-content-description">
      Identity and Access Management Platform will let you create applications, register users and manage identity providers to provide
      centralize authentication, authorization and user management features.
    </div>
    <div class="environment-content-actions">
      <a
        mat-raised-button
        color="primary"
        [routerLink]="['/environments', currentEnvironment.hrids[0], 'domains', 'new']"
        [disabled]="readonly"
        >Create a Security Domain</a
      >
      <span *ngIf="readonly">There is not enough permission, ask for support or wait for invitation to collaborate.</span>
    </div>
  </div>
</div>
